/**
 * Mock data for local testing without Dataverse
 * Simulates a typical CRM environment with accounts, contacts, opportunities, etc.
 */

import type { Entity, EntityRelationship } from '@/types';

// Common attribute types for reuse
const primaryIdField = (name: string, displayName: string) => ({
  name,
  displayName,
  type: 'UniqueIdentifier' as const,
  isPrimaryKey: true,
});

const stringField = (name: string, displayName: string) => ({
  name,
  displayName,
  type: 'String' as const,
});

const memoField = (name: string, displayName: string) => ({
  name,
  displayName,
  type: 'Memo' as const,
});

const integerField = (name: string, displayName: string) => ({
  name,
  displayName,
  type: 'Integer' as const,
});

const moneyField = (name: string, displayName: string) => ({
  name,
  displayName,
  type: 'Money' as const,
});

const dateTimeField = (name: string, displayName: string) => ({
  name,
  displayName,
  type: 'DateTime' as const,
});

const booleanField = (name: string, displayName: string) => ({
  name,
  displayName,
  type: 'Boolean' as const,
});

const picklistField = (name: string, displayName: string) => ({
  name,
  displayName,
  type: 'Picklist' as const,
});

const lookupField = (name: string, displayName: string, target: string) => ({
  name,
  displayName,
  type: 'Lookup' as const,
  isLookup: true,
  lookupTarget: target,
});

const ownerField = () => ({
  name: 'ownerid',
  displayName: 'Owner',
  type: 'Owner' as const,
  isLookup: true,
});

const stateField = () => ({
  name: 'statecode',
  displayName: 'Status',
  type: 'State' as const,
});

const statusField = () => ({
  name: 'statuscode',
  displayName: 'Status Reason',
  type: 'Status' as const,
});

const createdOnField = () => dateTimeField('createdon', 'Created On');
const modifiedOnField = () => dateTimeField('modifiedon', 'Modified On');

/**
 * Generate mock entities simulating a CRM system
 */
export function generateMockEntities(): Entity[] {
  return [
    // Account
    {
      logicalName: 'account',
      displayName: 'Account',
      objectTypeCode: 1,
      isCustomEntity: false,
      primaryIdAttribute: 'accountid',
      primaryNameAttribute: 'name',
      publisher: 'Microsoft',
      solutions: ['System'],
      attributes: [
        primaryIdField('accountid', 'Account'),
        stringField('name', 'Account Name'),
        stringField('accountnumber', 'Account Number'),
        stringField('telephone1', 'Main Phone'),
        stringField('emailaddress1', 'Email'),
        stringField('websiteurl', 'Website'),
        memoField('description', 'Description'),
        picklistField('industrycode', 'Industry'),
        moneyField('revenue', 'Annual Revenue'),
        integerField('numberofemployees', 'Number of Employees'),
        lookupField('primarycontactid', 'Primary Contact', 'contact'),
        lookupField('parentaccountid', 'Parent Account', 'account'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
      alternateKeys: [
        {
          logicalName: 'account_accountnumber',
          displayName: 'Account Number',
          keyAttributes: ['accountnumber'],
        },
        {
          logicalName: 'account_name_email',
          displayName: 'Name + Email',
          keyAttributes: ['name', 'emailaddress1'],
        },
      ],
    },
    // Contact
    {
      logicalName: 'contact',
      displayName: 'Contact',
      objectTypeCode: 2,
      isCustomEntity: false,
      primaryIdAttribute: 'contactid',
      primaryNameAttribute: 'fullname',
      publisher: 'Microsoft',
      solutions: ['System'],
      attributes: [
        primaryIdField('contactid', 'Contact'),
        stringField('fullname', 'Full Name'),
        stringField('firstname', 'First Name'),
        stringField('lastname', 'Last Name'),
        stringField('jobtitle', 'Job Title'),
        stringField('telephone1', 'Business Phone'),
        stringField('mobilephone', 'Mobile Phone'),
        stringField('emailaddress1', 'Email'),
        memoField('description', 'Description'),
        dateTimeField('birthdate', 'Birthday'),
        lookupField('parentcustomerid', 'Company Name', 'account'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
      alternateKeys: [
        {
          logicalName: 'contact_emailaddress1',
          displayName: 'Email Address',
          keyAttributes: ['emailaddress1'],
        },
      ],
    },
    // Opportunity
    {
      logicalName: 'opportunity',
      displayName: 'Opportunity',
      objectTypeCode: 3,
      isCustomEntity: false,
      primaryIdAttribute: 'opportunityid',
      primaryNameAttribute: 'name',
      publisher: 'Microsoft',
      solutions: ['Sales'],
      attributes: [
        primaryIdField('opportunityid', 'Opportunity'),
        stringField('name', 'Topic'),
        memoField('description', 'Description'),
        moneyField('estimatedvalue', 'Est. Revenue'),
        moneyField('actualvalue', 'Actual Revenue'),
        dateTimeField('estimatedclosedate', 'Est. Close Date'),
        dateTimeField('actualclosedate', 'Actual Close Date'),
        integerField('closeprobability', 'Probability'),
        picklistField('salesstage', 'Sales Stage'),
        lookupField('parentaccountid', 'Account', 'account'),
        lookupField('parentcontactid', 'Contact', 'contact'),
        lookupField('pricelevelid', 'Price List', 'pricelevel'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Lead
    {
      logicalName: 'lead',
      displayName: 'Lead',
      objectTypeCode: 4,
      isCustomEntity: false,
      primaryIdAttribute: 'leadid',
      primaryNameAttribute: 'fullname',
      publisher: 'Microsoft',
      solutions: ['Sales'],
      attributes: [
        primaryIdField('leadid', 'Lead'),
        stringField('fullname', 'Name'),
        stringField('firstname', 'First Name'),
        stringField('lastname', 'Last Name'),
        stringField('companyname', 'Company Name'),
        stringField('jobtitle', 'Job Title'),
        stringField('telephone1', 'Business Phone'),
        stringField('emailaddress1', 'Email'),
        memoField('description', 'Description'),
        moneyField('revenue', 'Annual Revenue'),
        picklistField('leadqualitycode', 'Rating'),
        picklistField('leadsourcecode', 'Lead Source'),
        lookupField('campaignid', 'Source Campaign', 'campaign'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Case/Incident
    {
      logicalName: 'incident',
      displayName: 'Case',
      objectTypeCode: 112,
      isCustomEntity: false,
      primaryIdAttribute: 'incidentid',
      primaryNameAttribute: 'title',
      publisher: 'Microsoft',
      solutions: ['Service'],
      attributes: [
        primaryIdField('incidentid', 'Case'),
        stringField('title', 'Case Title'),
        stringField('ticketnumber', 'Case Number'),
        memoField('description', 'Description'),
        picklistField('casetypecode', 'Case Type'),
        picklistField('prioritycode', 'Priority'),
        picklistField('caseorigincode', 'Origin'),
        dateTimeField('followupby', 'Follow Up By'),
        lookupField('customerid', 'Customer', 'account'),
        lookupField('primarycontactid', 'Contact', 'contact'),
        lookupField('productid', 'Product', 'product'),
        lookupField('subjectid', 'Subject', 'subject'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Product
    {
      logicalName: 'product',
      displayName: 'Product',
      objectTypeCode: 1024,
      isCustomEntity: false,
      primaryIdAttribute: 'productid',
      primaryNameAttribute: 'name',
      publisher: 'Microsoft',
      solutions: ['Product Catalog'],
      attributes: [
        primaryIdField('productid', 'Product'),
        stringField('name', 'Name'),
        stringField('productnumber', 'Product ID'),
        memoField('description', 'Description'),
        moneyField('price', 'List Price'),
        moneyField('standardcost', 'Standard Cost'),
        moneyField('currentcost', 'Current Cost'),
        integerField('quantityonhand', 'Quantity On Hand'),
        picklistField('productstructure', 'Product Structure'),
        lookupField('parentproductid', 'Parent', 'product'),
        lookupField('pricelevelid', 'Default Price List', 'pricelevel'),
        lookupField('subjectid', 'Subject', 'subject'),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
      alternateKeys: [
        {
          logicalName: 'product_productnumber',
          displayName: 'Product Number',
          keyAttributes: ['productnumber'],
        },
      ],
    },
    // Quote
    {
      logicalName: 'quote',
      displayName: 'Quote',
      objectTypeCode: 1084,
      isCustomEntity: false,
      primaryIdAttribute: 'quoteid',
      primaryNameAttribute: 'name',
      publisher: 'Microsoft',
      solutions: ['Sales'],
      attributes: [
        primaryIdField('quoteid', 'Quote'),
        stringField('name', 'Name'),
        stringField('quotenumber', 'Quote ID'),
        memoField('description', 'Description'),
        moneyField('totalamount', 'Total Amount'),
        moneyField('discountamount', 'Quote Discount'),
        dateTimeField('effectivefrom', 'Effective From'),
        dateTimeField('effectiveto', 'Effective To'),
        dateTimeField('expireson', 'Expires On'),
        lookupField('customerid', 'Potential Customer', 'account'),
        lookupField('opportunityid', 'Opportunity', 'opportunity'),
        lookupField('pricelevelid', 'Price List', 'pricelevel'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Order/Sales Order
    {
      logicalName: 'salesorder',
      displayName: 'Order',
      objectTypeCode: 1088,
      isCustomEntity: false,
      primaryIdAttribute: 'salesorderid',
      primaryNameAttribute: 'name',
      publisher: 'Microsoft',
      solutions: ['Sales'],
      attributes: [
        primaryIdField('salesorderid', 'Order'),
        stringField('name', 'Name'),
        stringField('ordernumber', 'Order ID'),
        memoField('description', 'Description'),
        moneyField('totalamount', 'Total Amount'),
        moneyField('discountamount', 'Order Discount'),
        dateTimeField('requestdeliveryby', 'Requested Delivery Date'),
        dateTimeField('datefulfilled', 'Date Fulfilled'),
        lookupField('customerid', 'Customer', 'account'),
        lookupField('opportunityid', 'Opportunity', 'opportunity'),
        lookupField('quoteid', 'Quote', 'quote'),
        lookupField('pricelevelid', 'Price List', 'pricelevel'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Invoice
    {
      logicalName: 'invoice',
      displayName: 'Invoice',
      objectTypeCode: 1090,
      isCustomEntity: false,
      primaryIdAttribute: 'invoiceid',
      primaryNameAttribute: 'name',
      publisher: 'Microsoft',
      solutions: ['Sales'],
      attributes: [
        primaryIdField('invoiceid', 'Invoice'),
        stringField('name', 'Name'),
        stringField('invoicenumber', 'Invoice ID'),
        memoField('description', 'Description'),
        moneyField('totalamount', 'Total Amount'),
        moneyField('discountamount', 'Invoice Discount'),
        dateTimeField('duedate', 'Due Date'),
        dateTimeField('datedelivered', 'Date Delivered'),
        lookupField('customerid', 'Customer', 'account'),
        lookupField('opportunityid', 'Opportunity', 'opportunity'),
        lookupField('salesorderid', 'Order', 'salesorder'),
        lookupField('pricelevelid', 'Price List', 'pricelevel'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Campaign
    {
      logicalName: 'campaign',
      displayName: 'Campaign',
      objectTypeCode: 4400,
      isCustomEntity: false,
      primaryIdAttribute: 'campaignid',
      primaryNameAttribute: 'name',
      publisher: 'Microsoft',
      solutions: ['Marketing'],
      attributes: [
        primaryIdField('campaignid', 'Campaign'),
        stringField('name', 'Name'),
        stringField('codename', 'Campaign Code'),
        memoField('description', 'Description'),
        moneyField('budgetedcost', 'Budget Allocated'),
        moneyField('totalactualcost', 'Total Cost of Campaign'),
        moneyField('expectedrevenue', 'Estimated Revenue'),
        dateTimeField('proposedstart', 'Proposed Start Date'),
        dateTimeField('proposedend', 'Proposed End Date'),
        dateTimeField('actualstart', 'Actual Start Date'),
        dateTimeField('actualend', 'Actual End Date'),
        picklistField('typecode', 'Campaign Type'),
        lookupField('pricelevelid', 'Price List', 'pricelevel'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Price List
    {
      logicalName: 'pricelevel',
      displayName: 'Price List',
      objectTypeCode: 1022,
      isCustomEntity: false,
      primaryIdAttribute: 'pricelevelid',
      primaryNameAttribute: 'name',
      publisher: 'Microsoft',
      solutions: ['Product Catalog'],
      attributes: [
        primaryIdField('pricelevelid', 'Price List'),
        stringField('name', 'Name'),
        memoField('description', 'Description'),
        dateTimeField('begindate', 'Start Date'),
        dateTimeField('enddate', 'End Date'),
        picklistField('freighttermscode', 'Freight Terms'),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Activity (base)
    {
      logicalName: 'activitypointer',
      displayName: 'Activity',
      objectTypeCode: 4200,
      isCustomEntity: false,
      primaryIdAttribute: 'activityid',
      primaryNameAttribute: 'subject',
      publisher: 'Microsoft',
      solutions: ['System'],
      attributes: [
        primaryIdField('activityid', 'Activity'),
        stringField('subject', 'Subject'),
        memoField('description', 'Description'),
        dateTimeField('scheduledstart', 'Start Time'),
        dateTimeField('scheduledend', 'End Time'),
        dateTimeField('actualstart', 'Actual Start'),
        dateTimeField('actualend', 'Actual End'),
        integerField('actualdurationminutes', 'Actual Duration'),
        picklistField('prioritycode', 'Priority'),
        lookupField('regardingobjectid', 'Regarding', 'account'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Task
    {
      logicalName: 'task',
      displayName: 'Task',
      objectTypeCode: 4212,
      isCustomEntity: false,
      primaryIdAttribute: 'activityid',
      primaryNameAttribute: 'subject',
      publisher: 'Microsoft',
      solutions: ['System'],
      attributes: [
        primaryIdField('activityid', 'Task'),
        stringField('subject', 'Subject'),
        memoField('description', 'Description'),
        dateTimeField('scheduledstart', 'Start Date'),
        dateTimeField('scheduledend', 'Due Date'),
        integerField('percentcomplete', 'Percent Complete'),
        picklistField('prioritycode', 'Priority'),
        lookupField('regardingobjectid', 'Regarding', 'account'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Email
    {
      logicalName: 'email',
      displayName: 'Email',
      objectTypeCode: 4202,
      isCustomEntity: false,
      primaryIdAttribute: 'activityid',
      primaryNameAttribute: 'subject',
      publisher: 'Microsoft',
      solutions: ['System'],
      attributes: [
        primaryIdField('activityid', 'Email'),
        stringField('subject', 'Subject'),
        memoField('description', 'Description'),
        stringField('torecipients', 'To'),
        stringField('ccrecipients', 'Cc'),
        stringField('bccrecipients', 'Bcc'),
        dateTimeField('senton', 'Date Sent'),
        booleanField('directioncode', 'Direction'),
        lookupField('regardingobjectid', 'Regarding', 'account'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Phone Call
    {
      logicalName: 'phonecall',
      displayName: 'Phone Call',
      objectTypeCode: 4210,
      isCustomEntity: false,
      primaryIdAttribute: 'activityid',
      primaryNameAttribute: 'subject',
      publisher: 'Microsoft',
      solutions: ['System'],
      attributes: [
        primaryIdField('activityid', 'Phone Call'),
        stringField('subject', 'Subject'),
        memoField('description', 'Description'),
        stringField('phonenumber', 'Phone Number'),
        integerField('actualdurationminutes', 'Duration'),
        booleanField('directioncode', 'Direction'),
        lookupField('regardingobjectid', 'Regarding', 'account'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Appointment
    {
      logicalName: 'appointment',
      displayName: 'Appointment',
      objectTypeCode: 4201,
      isCustomEntity: false,
      primaryIdAttribute: 'activityid',
      primaryNameAttribute: 'subject',
      publisher: 'Microsoft',
      solutions: ['System'],
      attributes: [
        primaryIdField('activityid', 'Appointment'),
        stringField('subject', 'Subject'),
        memoField('description', 'Description'),
        stringField('location', 'Location'),
        dateTimeField('scheduledstart', 'Start Time'),
        dateTimeField('scheduledend', 'End Time'),
        booleanField('isalldayevent', 'All Day Event'),
        lookupField('regardingobjectid', 'Regarding', 'account'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Subject (Knowledge Base Category)
    {
      logicalName: 'subject',
      displayName: 'Subject',
      objectTypeCode: 129,
      isCustomEntity: false,
      primaryIdAttribute: 'subjectid',
      primaryNameAttribute: 'title',
      publisher: 'Microsoft',
      solutions: ['System'],
      attributes: [
        primaryIdField('subjectid', 'Subject'),
        stringField('title', 'Title'),
        memoField('description', 'Description'),
        lookupField('parentsubject', 'Parent Subject', 'subject'),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Custom Entity 1: Project
    {
      logicalName: 'new_project',
      displayName: 'Project',
      objectTypeCode: 10001,
      isCustomEntity: true,
      primaryIdAttribute: 'new_projectid',
      primaryNameAttribute: 'new_name',
      publisher: 'Contoso',
      solutions: ['Project Management'],
      attributes: [
        primaryIdField('new_projectid', 'Project'),
        stringField('new_name', 'Project Name'),
        stringField('new_projectcode', 'Project Code'),
        memoField('new_description', 'Description'),
        moneyField('new_budget', 'Budget'),
        moneyField('new_actualcost', 'Actual Cost'),
        dateTimeField('new_startdate', 'Start Date'),
        dateTimeField('new_enddate', 'End Date'),
        integerField('new_percentcomplete', 'Percent Complete'),
        picklistField('new_status', 'Project Status'),
        picklistField('new_priority', 'Priority'),
        lookupField('new_accountid', 'Customer', 'account'),
        lookupField('new_primarycontactid', 'Project Manager', 'contact'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
      alternateKeys: [
        {
          logicalName: 'new_project_code',
          displayName: 'Project Code',
          keyAttributes: ['new_projectcode'],
        },
        {
          logicalName: 'new_project_account_name',
          displayName: 'Account + Project Name',
          keyAttributes: ['new_accountid', 'new_name'],
        },
      ],
    },
    // Custom Entity 2: Project Task
    {
      logicalName: 'new_projecttask',
      displayName: 'Project Task',
      objectTypeCode: 10002,
      isCustomEntity: true,
      primaryIdAttribute: 'new_projecttaskid',
      primaryNameAttribute: 'new_name',
      publisher: 'Contoso',
      solutions: ['Project Management'],
      attributes: [
        primaryIdField('new_projecttaskid', 'Project Task'),
        stringField('new_name', 'Task Name'),
        memoField('new_description', 'Description'),
        dateTimeField('new_startdate', 'Start Date'),
        dateTimeField('new_duedate', 'Due Date'),
        integerField('new_estimatedhours', 'Estimated Hours'),
        integerField('new_actualhours', 'Actual Hours'),
        integerField('new_percentcomplete', 'Percent Complete'),
        picklistField('new_status', 'Status'),
        picklistField('new_priority', 'Priority'),
        lookupField('new_projectid', 'Project', 'new_project'),
        lookupField('new_assignedto', 'Assigned To', 'contact'),
        lookupField('new_parenttaskid', 'Parent Task', 'new_projecttask'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Custom Entity 3: Time Entry
    {
      logicalName: 'new_timeentry',
      displayName: 'Time Entry',
      objectTypeCode: 10003,
      isCustomEntity: true,
      primaryIdAttribute: 'new_timeentryid',
      primaryNameAttribute: 'new_name',
      publisher: 'Contoso',
      solutions: ['Project Management'],
      attributes: [
        primaryIdField('new_timeentryid', 'Time Entry'),
        stringField('new_name', 'Description'),
        dateTimeField('new_date', 'Date'),
        { name: 'new_duration', displayName: 'Duration (Hours)', type: 'Decimal' as const },
        memoField('new_notes', 'Notes'),
        booleanField('new_billable', 'Billable'),
        picklistField('new_type', 'Entry Type'),
        lookupField('new_projectid', 'Project', 'new_project'),
        lookupField('new_projecttaskid', 'Project Task', 'new_projecttask'),
        lookupField('new_resourceid', 'Resource', 'contact'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Custom Entity 4: Expense
    {
      logicalName: 'new_expense',
      displayName: 'Expense',
      objectTypeCode: 10004,
      isCustomEntity: true,
      primaryIdAttribute: 'new_expenseid',
      primaryNameAttribute: 'new_name',
      publisher: 'Contoso',
      solutions: ['Project Management'],
      attributes: [
        primaryIdField('new_expenseid', 'Expense'),
        stringField('new_name', 'Expense Name'),
        memoField('new_description', 'Description'),
        dateTimeField('new_expensedate', 'Expense Date'),
        moneyField('new_amount', 'Amount'),
        picklistField('new_category', 'Category'),
        booleanField('new_billable', 'Billable'),
        booleanField('new_reimbursable', 'Reimbursable'),
        lookupField('new_projectid', 'Project', 'new_project'),
        lookupField('new_submittedby', 'Submitted By', 'contact'),
        ownerField(),
        stateField(),
        statusField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // User (System User)
    {
      logicalName: 'systemuser',
      displayName: 'User',
      objectTypeCode: 8,
      isCustomEntity: false,
      primaryIdAttribute: 'systemuserid',
      primaryNameAttribute: 'fullname',
      publisher: 'Microsoft',
      solutions: ['System'],
      attributes: [
        primaryIdField('systemuserid', 'User'),
        stringField('fullname', 'Full Name'),
        stringField('firstname', 'First Name'),
        stringField('lastname', 'Last Name'),
        stringField('domainname', 'User Name'),
        stringField('internalemailaddress', 'Primary Email'),
        stringField('title', 'Title'),
        stringField('mobilephone', 'Mobile Phone'),
        booleanField('isdisabled', 'Status'),
        lookupField('businessunitid', 'Business Unit', 'businessunit'),
        lookupField('parentsystemuserid', 'Manager', 'systemuser'),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Team
    {
      logicalName: 'team',
      displayName: 'Team',
      objectTypeCode: 9,
      isCustomEntity: false,
      primaryIdAttribute: 'teamid',
      primaryNameAttribute: 'name',
      publisher: 'Microsoft',
      solutions: ['System'],
      attributes: [
        primaryIdField('teamid', 'Team'),
        stringField('name', 'Team Name'),
        memoField('description', 'Description'),
        stringField('emailaddress', 'Email'),
        lookupField('businessunitid', 'Business Unit', 'businessunit'),
        lookupField('administratorid', 'Administrator', 'systemuser'),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Business Unit
    {
      logicalName: 'businessunit',
      displayName: 'Business Unit',
      objectTypeCode: 10,
      isCustomEntity: false,
      primaryIdAttribute: 'businessunitid',
      primaryNameAttribute: 'name',
      publisher: 'Microsoft',
      solutions: ['System'],
      attributes: [
        primaryIdField('businessunitid', 'Business Unit'),
        stringField('name', 'Name'),
        memoField('description', 'Description'),
        stringField('divisionname', 'Division'),
        stringField('emailaddress', 'Email'),
        stringField('websiteurl', 'Website'),
        lookupField('parentbusinessunitid', 'Parent Business', 'businessunit'),
        booleanField('isdisabled', 'Is Disabled'),
        createdOnField(),
        modifiedOnField(),
      ],
    },
    // Note/Annotation
    {
      logicalName: 'annotation',
      displayName: 'Note',
      objectTypeCode: 5,
      isCustomEntity: false,
      primaryIdAttribute: 'annotationid',
      primaryNameAttribute: 'subject',
      publisher: 'Microsoft',
      solutions: ['System'],
      attributes: [
        primaryIdField('annotationid', 'Note'),
        stringField('subject', 'Title'),
        memoField('notetext', 'Description'),
        stringField('filename', 'File Name'),
        integerField('filesize', 'File Size (Bytes)'),
        stringField('mimetype', 'Mime Type'),
        booleanField('isdocument', 'Is Document'),
        lookupField('objectid', 'Regarding', 'account'),
        ownerField(),
        createdOnField(),
        modifiedOnField(),
      ],
    },
  ];
}

/**
 * Generate mock relationships based on entities
 */
export function generateMockRelationships(): EntityRelationship[] {
  return [
    // Account relationships
    {
      schemaName: 'contact_customer_accounts',
      from: 'contact',
      to: 'account',
      type: 'N:1',
      referencingAttribute: 'parentcustomerid',
      referencedAttribute: 'accountid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'account_primary_contact',
      from: 'account',
      to: 'contact',
      type: 'N:1',
      referencingAttribute: 'primarycontactid',
      referencedAttribute: 'contactid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'account_parent_account',
      from: 'account',
      to: 'account',
      type: 'N:1',
      referencingAttribute: 'parentaccountid',
      referencedAttribute: 'accountid',
      relationshipType: 'OneToManyRelationship',
    },
    // Opportunity relationships
    {
      schemaName: 'opportunity_parent_account',
      from: 'opportunity',
      to: 'account',
      type: 'N:1',
      referencingAttribute: 'parentaccountid',
      referencedAttribute: 'accountid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'opportunity_parent_contact',
      from: 'opportunity',
      to: 'contact',
      type: 'N:1',
      referencingAttribute: 'parentcontactid',
      referencedAttribute: 'contactid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'opportunity_price_level',
      from: 'opportunity',
      to: 'pricelevel',
      type: 'N:1',
      referencingAttribute: 'pricelevelid',
      referencedAttribute: 'pricelevelid',
      relationshipType: 'OneToManyRelationship',
    },
    // Case relationships
    {
      schemaName: 'incident_customer_accounts',
      from: 'incident',
      to: 'account',
      type: 'N:1',
      referencingAttribute: 'customerid',
      referencedAttribute: 'accountid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'incident_primarycontact',
      from: 'incident',
      to: 'contact',
      type: 'N:1',
      referencingAttribute: 'primarycontactid',
      referencedAttribute: 'contactid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'incident_product',
      from: 'incident',
      to: 'product',
      type: 'N:1',
      referencingAttribute: 'productid',
      referencedAttribute: 'productid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'incident_subject',
      from: 'incident',
      to: 'subject',
      type: 'N:1',
      referencingAttribute: 'subjectid',
      referencedAttribute: 'subjectid',
      relationshipType: 'OneToManyRelationship',
    },
    // Lead relationships
    {
      schemaName: 'lead_campaign',
      from: 'lead',
      to: 'campaign',
      type: 'N:1',
      referencingAttribute: 'campaignid',
      referencedAttribute: 'campaignid',
      relationshipType: 'OneToManyRelationship',
    },
    // Quote relationships
    {
      schemaName: 'quote_customer_accounts',
      from: 'quote',
      to: 'account',
      type: 'N:1',
      referencingAttribute: 'customerid',
      referencedAttribute: 'accountid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'quote_opportunity',
      from: 'quote',
      to: 'opportunity',
      type: 'N:1',
      referencingAttribute: 'opportunityid',
      referencedAttribute: 'opportunityid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'quote_pricelevel',
      from: 'quote',
      to: 'pricelevel',
      type: 'N:1',
      referencingAttribute: 'pricelevelid',
      referencedAttribute: 'pricelevelid',
      relationshipType: 'OneToManyRelationship',
    },
    // Order relationships
    {
      schemaName: 'order_customer_accounts',
      from: 'salesorder',
      to: 'account',
      type: 'N:1',
      referencingAttribute: 'customerid',
      referencedAttribute: 'accountid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'order_opportunity',
      from: 'salesorder',
      to: 'opportunity',
      type: 'N:1',
      referencingAttribute: 'opportunityid',
      referencedAttribute: 'opportunityid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'order_quote',
      from: 'salesorder',
      to: 'quote',
      type: 'N:1',
      referencingAttribute: 'quoteid',
      referencedAttribute: 'quoteid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'order_pricelevel',
      from: 'salesorder',
      to: 'pricelevel',
      type: 'N:1',
      referencingAttribute: 'pricelevelid',
      referencedAttribute: 'pricelevelid',
      relationshipType: 'OneToManyRelationship',
    },
    // Invoice relationships
    {
      schemaName: 'invoice_customer_accounts',
      from: 'invoice',
      to: 'account',
      type: 'N:1',
      referencingAttribute: 'customerid',
      referencedAttribute: 'accountid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'invoice_opportunity',
      from: 'invoice',
      to: 'opportunity',
      type: 'N:1',
      referencingAttribute: 'opportunityid',
      referencedAttribute: 'opportunityid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'invoice_salesorder',
      from: 'invoice',
      to: 'salesorder',
      type: 'N:1',
      referencingAttribute: 'salesorderid',
      referencedAttribute: 'salesorderid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'invoice_pricelevel',
      from: 'invoice',
      to: 'pricelevel',
      type: 'N:1',
      referencingAttribute: 'pricelevelid',
      referencedAttribute: 'pricelevelid',
      relationshipType: 'OneToManyRelationship',
    },
    // Product relationships
    {
      schemaName: 'product_parent_product',
      from: 'product',
      to: 'product',
      type: 'N:1',
      referencingAttribute: 'parentproductid',
      referencedAttribute: 'productid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'product_pricelevel',
      from: 'product',
      to: 'pricelevel',
      type: 'N:1',
      referencingAttribute: 'pricelevelid',
      referencedAttribute: 'pricelevelid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'product_subject',
      from: 'product',
      to: 'subject',
      type: 'N:1',
      referencingAttribute: 'subjectid',
      referencedAttribute: 'subjectid',
      relationshipType: 'OneToManyRelationship',
    },
    // Campaign relationships
    {
      schemaName: 'campaign_pricelevel',
      from: 'campaign',
      to: 'pricelevel',
      type: 'N:1',
      referencingAttribute: 'pricelevelid',
      referencedAttribute: 'pricelevelid',
      relationshipType: 'OneToManyRelationship',
    },
    // Activity relationships
    {
      schemaName: 'activity_regarding_account',
      from: 'activitypointer',
      to: 'account',
      type: 'N:1',
      referencingAttribute: 'regardingobjectid',
      referencedAttribute: 'accountid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'task_regarding_account',
      from: 'task',
      to: 'account',
      type: 'N:1',
      referencingAttribute: 'regardingobjectid',
      referencedAttribute: 'accountid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'email_regarding_account',
      from: 'email',
      to: 'account',
      type: 'N:1',
      referencingAttribute: 'regardingobjectid',
      referencedAttribute: 'accountid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'phonecall_regarding_account',
      from: 'phonecall',
      to: 'account',
      type: 'N:1',
      referencingAttribute: 'regardingobjectid',
      referencedAttribute: 'accountid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'appointment_regarding_account',
      from: 'appointment',
      to: 'account',
      type: 'N:1',
      referencingAttribute: 'regardingobjectid',
      referencedAttribute: 'accountid',
      relationshipType: 'OneToManyRelationship',
    },
    // Subject self-reference
    {
      schemaName: 'subject_parent_subject',
      from: 'subject',
      to: 'subject',
      type: 'N:1',
      referencingAttribute: 'parentsubject',
      referencedAttribute: 'subjectid',
      relationshipType: 'OneToManyRelationship',
    },
    // Custom entity relationships - Project
    {
      schemaName: 'new_project_account',
      from: 'new_project',
      to: 'account',
      type: 'N:1',
      referencingAttribute: 'new_accountid',
      referencedAttribute: 'accountid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'new_project_contact',
      from: 'new_project',
      to: 'contact',
      type: 'N:1',
      referencingAttribute: 'new_primarycontactid',
      referencedAttribute: 'contactid',
      relationshipType: 'OneToManyRelationship',
    },
    // Custom entity relationships - Project Task
    {
      schemaName: 'new_projecttask_project',
      from: 'new_projecttask',
      to: 'new_project',
      type: 'N:1',
      referencingAttribute: 'new_projectid',
      referencedAttribute: 'new_projectid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'new_projecttask_contact',
      from: 'new_projecttask',
      to: 'contact',
      type: 'N:1',
      referencingAttribute: 'new_assignedto',
      referencedAttribute: 'contactid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'new_projecttask_parent',
      from: 'new_projecttask',
      to: 'new_projecttask',
      type: 'N:1',
      referencingAttribute: 'new_parenttaskid',
      referencedAttribute: 'new_projecttaskid',
      relationshipType: 'OneToManyRelationship',
    },
    // Custom entity relationships - Time Entry
    {
      schemaName: 'new_timeentry_project',
      from: 'new_timeentry',
      to: 'new_project',
      type: 'N:1',
      referencingAttribute: 'new_projectid',
      referencedAttribute: 'new_projectid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'new_timeentry_projecttask',
      from: 'new_timeentry',
      to: 'new_projecttask',
      type: 'N:1',
      referencingAttribute: 'new_projecttaskid',
      referencedAttribute: 'new_projecttaskid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'new_timeentry_contact',
      from: 'new_timeentry',
      to: 'contact',
      type: 'N:1',
      referencingAttribute: 'new_resourceid',
      referencedAttribute: 'contactid',
      relationshipType: 'OneToManyRelationship',
    },
    // Custom entity relationships - Expense
    {
      schemaName: 'new_expense_project',
      from: 'new_expense',
      to: 'new_project',
      type: 'N:1',
      referencingAttribute: 'new_projectid',
      referencedAttribute: 'new_projectid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'new_expense_contact',
      from: 'new_expense',
      to: 'contact',
      type: 'N:1',
      referencingAttribute: 'new_submittedby',
      referencedAttribute: 'contactid',
      relationshipType: 'OneToManyRelationship',
    },
    // System user relationships
    {
      schemaName: 'systemuser_businessunit',
      from: 'systemuser',
      to: 'businessunit',
      type: 'N:1',
      referencingAttribute: 'businessunitid',
      referencedAttribute: 'businessunitid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'systemuser_manager',
      from: 'systemuser',
      to: 'systemuser',
      type: 'N:1',
      referencingAttribute: 'parentsystemuserid',
      referencedAttribute: 'systemuserid',
      relationshipType: 'OneToManyRelationship',
    },
    // Team relationships
    {
      schemaName: 'team_businessunit',
      from: 'team',
      to: 'businessunit',
      type: 'N:1',
      referencingAttribute: 'businessunitid',
      referencedAttribute: 'businessunitid',
      relationshipType: 'OneToManyRelationship',
    },
    {
      schemaName: 'team_administrator',
      from: 'team',
      to: 'systemuser',
      type: 'N:1',
      referencingAttribute: 'administratorid',
      referencedAttribute: 'systemuserid',
      relationshipType: 'OneToManyRelationship',
    },
    // Business unit self-reference
    {
      schemaName: 'businessunit_parentbusinessunit',
      from: 'businessunit',
      to: 'businessunit',
      type: 'N:1',
      referencingAttribute: 'parentbusinessunitid',
      referencedAttribute: 'businessunitid',
      relationshipType: 'OneToManyRelationship',
    },
    // Note/Annotation relationships
    {
      schemaName: 'annotation_account',
      from: 'annotation',
      to: 'account',
      type: 'N:1',
      referencingAttribute: 'objectid',
      referencedAttribute: 'accountid',
      relationshipType: 'OneToManyRelationship',
    },
  ];
}

/**
 * Simulate API delay for more realistic testing
 */
export function simulateDelay(ms: number = 500): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}
