name: Question
description: Ask a question about using Dataverse ERD Visualizer
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide as much context as possible.

  - type: dropdown
    id: category
    attributes:
      label: Question category
      description: What area does your question relate to?
      options:
        - Installation / Setup
        - Deployment to Dataverse
        - Using the application
        - Export features
        - Performance / Optimization
        - Customization
        - Integration with other tools
        - Contributing / Development
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: Ask your question here. Be as specific as possible.
      placeholder: |
        How can I filter entities to only show custom tables?

        I've tried using the sidebar filters but I can't figure out how to exclude
        all the system tables and only show my custom entities.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context that might help us answer your question.
      placeholder: |
        - I'm running the tool in a Dynamics 365 Sales environment
        - I have about 200 entities total, but only 30 are custom
        - I'm using the managed solution from the releases page
    validations:
      required: false

  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
      description: Let us know what you've already attempted.
      placeholder: |
        - I looked in the documentation but couldn't find this specific use case
        - I tried using the publisher filter but it shows all publishers
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your question.
      placeholder: Drag and drop images here or paste from clipboard.
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running the application?
      options:
        - Dataverse / Model-driven App
        - Local Development (npm run dev)
        - Not applicable
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm
      options:
        - label: I have searched existing issues and discussions for an answer
          required: true
        - label: I have read the README and documentation
          required: false
